{"event": "verbose", "uuid": "591bfe8c-ee52-45dd-b29e-0ac3bc25650f", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/tmp/tmpa36iad1u.yml': line 12, column 7, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "070f94ec-556c-4bb8-b728-099995cbfe61", "created": "2025-05-17T19:48:42.537766+00:00"}