{"event": "verbose", "uuid": "ed3f91be-c4eb-44a9-8a52-fcef5643f833", "counter": 5, "stdout": "\u001b[0;31mThe error appears to be in '/tmp/tmpvarlmq1s.yml': line 63, column 7, but may\u001b[0m", "start_line": 4, "end_line": 5, "runner_ident": "f37d1b49-dcaf-404d-8953-46680f143a76", "created": "2025-05-17T11:05:04.993323+00:00"}