{"event": "verbose", "uuid": "fd6846da-f3ad-4c81-876e-6736bcf089d5", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/tmp/tmppdx5zss4.yml': line 228, column 7, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "655ec1dd-bbd9-4816-84a3-be3e49fe150d", "created": "2025-05-15T18:07:24.842459+00:00"}