{"uuid": "1b5c7123-1230-4d0f-9685-7f81c384b286", "counter": 53, "stdout": "\u001b[0;31mfatal: [demo03]: FAILED! => {\"changed\": false, \"msg\": \"Unable to start service vsftpd: Job for vsftpd.service failed because the control process exited with error code.\\nSee \\\"systemctl status vsftpd.service\\\" and \\\"journalctl -xeu vsftpd.service\\\" for details.\\n\"}\u001b[0m\r\n\u001b[0;36m...ignoring\u001b[0m", "start_line": 71, "end_line": 73, "runner_ident": "5aeda149-c0c4-4518-a37f-9a6e3932e973", "event": "runner_on_failed", "pid": 160671, "created": "2025-05-15T17:40:40.051082+00:00", "parent_uuid": "005056b7-f67d-57f5-f409-000000000012", "event_data": {"playbook": "/tmp/tmpw1i036m9.yml", "playbook_uuid": "30f74d1c-0d4b-465e-86b3-36ebb2c3833d", "play": "Soluci\u00f3n final para VSFTPD", "play_uuid": "005056b7-f67d-57f5-f409-000000000002", "play_pattern": "demo03", "task": "Reiniciar VSFTPD", "task_uuid": "005056b7-f67d-57f5-f409-000000000012", "task_action": "service", "resolved_action": "ansible.builtin.service", "task_args": "", "task_path": "/tmp/tmpw1i036m9.yml:169", "host": "demo03", "remote_addr": "demo03", "res": {"msg": "Unable to start service vsftpd: Job for vsftpd.service failed because the control process exited with error code.\nSee \"systemctl status vsftpd.service\" and \"journalctl -xeu vsftpd.service\" for details.\n", "invocation": {"module_args": {"name": "vsftpd", "state": "restarted", "enabled": true, "daemon_reload": false, "daemon_reexec": false, "scope": "system", "no_block": false, "force": null, "masked": null}}, "_ansible_no_log": false, "changed": false}, "start": "2025-05-15T17:40:36.038883+00:00", "end": "2025-05-15T17:40:40.050686+00:00", "duration": 4.011803, "ignore_errors": true, "event_loop": null, "uuid": "1b5c7123-1230-4d0f-9685-7f81c384b286"}}