{"event": "verbose", "uuid": "4d020ea0-1733-4ee5-98ec-b753864954a7", "counter": 4, "stdout": "\u001b[0;31mThe error appears to be in '/tmp/tmpfkw54_3z.yml': line 170, column 11, but may\u001b[0m", "start_line": 3, "end_line": 4, "runner_ident": "a6538b6f-db55-4c46-8a51-3e8a9ddc73b4", "created": "2025-05-17T01:27:36.994350+00:00"}