{"uuid": "0bce99d5-d16e-449d-9482-bb420cd08219", "counter": 34, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option\u001b[0m\r\n\u001b[0;31mfatal: [demo03]: FAILED! => {\"changed\": false, \"msg\": \"Could not find or access '/opt/www/media/templates/httpd.conf.j2' on the Ansible Controller.\\nIf you are using a module and expect the file to exist on the remote, see the remote_src option\"}\u001b[0m", "start_line": 31, "end_line": 33, "runner_ident": "ccb716ed-32c2-4079-ade7-29540360c0c8", "event": "runner_on_failed", "pid": 102849, "created": "2025-05-17T01:08:39.820386+00:00", "parent_uuid": "005056b7-f67d-1591-f649-00000000000f", "event_data": {"playbook": "/tmp/tmp_nr13i5c.yml", "playbook_uuid": "4e6e19b3-0feb-4ff7-b965-f42139d74ab2", "play": "Configuraci\u00f3n completa de servidor web con HTTPS", "play_uuid": "005056b7-f67d-1591-f649-000000000002", "play_pattern": "demo03", "task": "Configurar archivo httpd.conf", "task_uuid": "005056b7-f67d-1591-f649-00000000000f", "task_action": "template", "resolved_action": "ansible.builtin.template", "task_args": "", "task_path": "/tmp/tmp_nr13i5c.yml:66", "host": "demo03", "remote_addr": "demo03", "res": {"msg": "Could not find or access '/opt/www/media/templates/httpd.conf.j2' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option", "exception": "Traceback (most recent call last):\n  File \"/usr/lib/python3.9/site-packages/ansible/plugins/action/template.py\", line 85, in run\n    source = self._find_needle('templates', source)\n  File \"/usr/lib/python3.9/site-packages/ansible/plugins/action/__init__.py\", line 1431, in _find_needle\n    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)\n  File \"/usr/lib/python3.9/site-packages/ansible/parsing/dataloader.py\", line 341, in path_dwim_relative_stack\n    raise AnsibleFileNotFound(file_name=source, paths=[to_native(p) for p in search])\nansible.errors.AnsibleFileNotFound: Could not find or access '/opt/www/media/templates/httpd.conf.j2' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option\n", "_ansible_no_log": false, "changed": false}, "start": "2025-05-17T01:08:39.508056+00:00", "end": "2025-05-17T01:08:39.819970+00:00", "duration": 0.311914, "ignore_errors": null, "event_loop": null, "uuid": "0bce99d5-d16e-449d-9482-bb420cd08219"}}