{"uuid": "9b2e6742-93f3-4afa-b9bb-81f3c2fa20c1", "counter": 5, "stdout": "\u001b[1;35m[WARNING]: Unhandled error in Python interpreter discovery for host\u001b[0m\r\n\u001b[1;35m10.104.10.20: unexpected output from Python interpreter discovery\u001b[0m", "start_line": 4, "end_line": 6, "runner_ident": "5c8a7740-47dd-4882-a7b3-fb7278f96579", "event": "warning", "pid": 229635, "created": "2025-05-17T23:21:42.979602+00:00", "parent_uuid": "005056b7-f67d-b424-c4b0-000000000004", "event_data": {"playbook": "/tmp/tmpnkv8gudh.yml", "playbook_uuid": "ce24bf21-1d93-4429-af9b-719fd044fa2f", "play": "Pruebas b\u00e1sicas de conectividad y sistema en Windows", "play_uuid": "005056b7-f67d-b424-c4b0-000000000002", "play_pattern": "target_host", "task": "Verificar conectividad b\u00e1sica con ping", "task_uuid": "005056b7-f67d-b424-c4b0-000000000004", "task_action": "command", "resolved_action": "ansible.builtin.command", "task_args": "", "task_path": "/tmp/tmpnkv8gudh.yml:7", "warning": true, "uuid": "9b2e6742-93f3-4afa-b9bb-81f3c2fa20c1"}}