{"event": "verbose", "uuid": "6f9da5ac-9098-4f00-9da0-8d048b15d3ab", "counter": 65, "stdout": "\u001b[0;31mThe error appears to be in '/tmp/tmpvcpjcpyi.yml': line 36, column 7, but may\u001b[0m", "start_line": 64, "end_line": 65, "runner_ident": "95cdc147-804c-4ccb-a4cb-27d87c974fdb", "created": "2025-05-18T02:04:51.761859+00:00"}